### ISSUE TITLE
Throw ValidationError rather than returning invalid object 

### ISSUE THREAD

**Issue by atkinchris** [JCMais/graphql-yup-middleware#1]
If a validation error occurs, the middleware will return an object with a key of `error`. GraphQL will return this to the client as a valid query/mutation, with a field of `error`. This is not a standard GraphQL error format (which instead includes stacktraces and a field called `errors`). 

https://github.com/JCMais/graphql-yup-middleware/blob/ce531ee317dccb95be201d356806f508ef47ab58/src/yupMiddleware.ts#L119-L121

The middleware should instead throw a `ValidationError` and allow the GraphQL server to handle and wrap this up for the client.

**Comment by JCMais** [comment]
Hi, thanks for opening an issue to discuss that.

The error object you are mentioning should not be used for user errors (like user input errors), they must only be used for exceptions. GraphQL itself only throws those when there is something wrong on the query itself, like an invalid field.

The format of the error object returned by the middleware itself is really simple, it's more like an example than anything, it's up the library user to use their own error formatter, using the `errorPayloadBuilder` option.

**Comment by atkinchris** [comment]
Thanks for the response - that explains it.

We've chosen to use GraphQL's `errors` block rather than payload specific `error` fields, so we'll adapt a minimal middleware (from your article https://itnext.io/graphql-mutation-arguments-validation-with-yup-using-graphql-middleware-645822fb748) to suit instead.

**Comment by JCMais** [comment]
No problem, glad to hear that that post is being useful! 😄
