### ISSUE TITLE
Inject MutationValidationErrorType and FieldValidationErrorType with graphql-js GraphQLSchema

### ISSUE THREAD

**Issue by danwetherald** [JCMais/graphql-yup-middleware#10]
I am not sure how we would get the validation error types into our schema when using the GraphQLSchema class from https://graphql.org/graphql-js/type/#graphqlschema

Any help would be much appreciated!

**Comment by JCMais** [comment]
See [example here](https://github.com/JCMais/graphql-yup-middleware/blob/master/examples/graphql-js/src/index.ts)
