### ISSUE TITLE
Mutation inputs validation

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [JCMais/graphql-yup-middleware#2]
@JCMais Is it possible to validate mutation inputs like:

```graphql
type Mutation {
  createUser(data: UserCreateInput!): User!
}

input UserCreateInput {
  name: String
  phone: String
  email: String!
}
```

instead of mutation arguments like:

```graphql
type Mutation {
  createUser(name: String, phone: String, email: String!): User!
}
```

Problem: e.g. [Prisma](https://github.com/prisma/prisma) extracts all query/mutation arguments to separate input types when generates schema from datamodel.

**Comment by JCMais** [comment]
@FluorescentHallucinogen there has been some time since I last touched this library, but if I recall correcttly you can do:
```javascript
{
  validationSchema: yup.object().shape({
    data: yup.object().shape({
      // ... your validation here
    }),
  }),
}
```

**Comment by mathieug** [comment]
> @FluorescentHallucinogen there has been some time since I last touched this library, but if I recall correcttly you can do:
> 
> ```js
> {
>   validationSchema: yup.object().shape({
>     data: yup.object().shape({
>       // ... your validation here
>     }),
>   }),
> }
> ```

I would say:
```js
   validationSchema: yup.object().shape({
     input: yup.object().required().shape({
       // ... your validation here
     }),
   }),
```

@JCMais do you confirm the `required()` on the `input` is useful or not?

**Comment by JCMais** [comment]
@mathieug `required()` is not required, see: https://codesandbox.io/s/yup-id2jq
