### ISSUE TITLE
Partial execution

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [JCMais/graphql-yup-middleware#3]
@JCMais

The _partial response_ is one of the basic principles of GraphQL: a response may contain both a partial `data` as well as encountered `errors` in the case that a field error occurred on a field which was replaced with `null`.

If a field’s resolve function throws an error, the error will be inserted into the response’s `errors` key and the field will resolve to `null`.

If a a null value returns in a resolver for a non-null field, the null result bubbles up to the nearest nullable parent.

This is what concerns data querying (reading). But what about data mutating (writing)?

Suppose there is a mutation that has 3 arguments, and we add validations to all these arguments.

Current behavior: if at least one of the mutation arguments fails validation, the entire mutation will not be executed. Right?

But what if this argument (which failed validation) is not non-null (optional / not required)? In this case the mutation could be executed with two rest arguments.

Is it possible to just remove this argument from mutation if it fails validation?

**Comment by JCMais** [comment]
In my opinion, if an optional field fails validation it should still fail the whole mutation, the data is invalid anyway, the client is responsible for not sending the data if that is the case.

If you really need this, you can recreate the behavior of this library and extend with your own following the medium article on the Readme.md.
