### ISSUE TITLE
not working with graphql v15

### ISSUE THREAD

**Issue by sibelius** [JCMais/graphql-yup-middleware#5]
graphql v15 is more strict about graphql fields

you need to move them to `extensions`

**Comment by mymywang** [comment]
@sibelius Which `extensions` did you refer to? Could you add link to the doc if there's any? I'm also looking into other options. Thanks!

**Comment by sibelius** [comment]
```jsx
export const getMutationExtensions = (
  info: GraphQLResolveInfo,
  mutationName: string,
): GraphQLFieldConfigMap<any, GraphQLContext> | null => {
  const mutationType = info.schema.getMutationType();
  if (!mutationType) {
    return null;
  }

  const fields = mutationType.getFields();

  return fields[mutationName].extensions;
};
```

on v14 graphql returned everything inside `getFields()`, however now, you need to explicit use `extensions` to store yup schema or something else

**Comment by JCMais** [comment]
@mymywang it's related to this proposal that was added on GraphQL 15: https://github.com/graphql/graphql-js/issues/1527

I should be able to do something about it this weekend.

**Comment by JCMais** [comment]
I've pushed `graphql-yup-middleware@next` as a pre-release version with support for the extensions field, the readme was updated accordingly. Anyone is welcome to test it and post feedback here.

**Comment by jgcmarins** [comment]
That's awesome!
I'll give a try ASAP and bring feedback.

**Comment by JCMais** [comment]
`graphql-yup-middleware@1.0.0` has been released with support to (only) GraphQL v15 using the extensions field.
