### ISSUE TITLE
Improve GraphQL type augmentation - Extensions field

### ISSUE THREAD

**Issue by JCMais** [JCMais/graphql-yup-middleware#8]
This needs https://github.com/graphql/graphql-js/pull/2465 to be merged

**Comment by gajus** [comment]
The referenced PR has now been merged.

**Comment by JCMais** [comment]
`graphql-yup-middleware@1.0.0` has been released with support to (only) GraphQL v15 using the extensions field  + the most recent version of `graphql-middleware`.
